// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8Q9X2Y3Z4A5B6C7D8E9F0G1H2I3J4K',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'nutrients1-36408159',
    authDomain: 'nutrients1-36408159.firebaseapp.com',
    storageBucket: 'nutrients1-36408159.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8Q9X2Y3Z4A5B6C7D8E9F0G1H2I3J4K',
    appId: '1:123456789012:android:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'nutrients1-36408159',
    storageBucket: 'nutrients1-36408159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8Q9X2Y3Z4A5B6C7D8E9F0G1H2I3J4K',
    appId: '1:123456789012:ios:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'nutrients1-36408159',
    storageBucket: 'nutrients1-36408159.appspot.com',
    iosBundleId: 'com.example.sih2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8Q9X2Y3Z4A5B6C7D8E9F0G1H2I3J4K',
    appId: '1:123456789012:macos:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'nutrients1-36408159',
    storageBucket: 'nutrients1-36408159.appspot.com',
    iosBundleId: 'com.example.sih2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQZ8Q9X2Y3Z4A5B6C7D8E9F0G1H2I3J4K',
    appId: '1:123456789012:windows:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'nutrients1-36408159',
    authDomain: 'nutrients1-36408159.firebaseapp.com',
    storageBucket: 'nutrients1-36408159.appspot.com',
  );
}